apiVersion: apps/v1
kind: Deployment
metadata:
  name: kub-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes
  template:
    metadata:
      labels:
        app: kubernetes
    spec:
      containers:
      - name: kubernetes
        image: langston8182/kubernetes:0.0.4-SNAPSHOT
        env:
        - name: DATABASE_HOST
          value: db-services
        - name: DATABASE_PORT
          value: "3307"
        - name: DATABASE_DB
          value: kubernetes
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: db_user
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: db_password
      imagePullSecrets:
      - name: kub-secret