apiVersion: v1
kind: Service
metadata:
  name: kub-services
  labels:
    app: kubernetes
spec:
  selector:
    app: kubernetes
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 31100
